{
  cfg,
  lib,
  tomlFormat,
  ...
}:
let
  shellIntegrationStr = ''
    source "${cfg.package}/etc/profile.d/wezterm.sh"
  '';
in
lib.mkIf cfg.enable {
  home.packages = [ cfg.package ];

  xdg.configFile = lib.mkMerge [
    # 1. The Main `wezterm.lua` Entry Point
    {
      "wezterm/wezterm.lua".text = ''
        -- Generated by Home Manager.
        -- See https://wezfurlong.org/wezterm/

        local wezterm = require 'wezterm'
        local config = wezterm.config_builder() -- [[@as Wezterm]]

        ${lib.concatLines (
          lib.mapAttrsToList (name: _: ''require("modules.${name}").apply_to_config(config)'') cfg.extraConfig
        )}

        return config
      '';
    }

    # 2. The Dynamic Modules (mapped from extraConfig)
    (lib.mapAttrs' (
      name: value:
      let
        # Convert "keybinds.overrides" -> "keybinds/overrides"
        pathName = builtins.replaceStrings [ "." ] [ "/" ] name;
        targetPath = "wezterm/modules/${pathName}.lua";
      in
      # Check if value is a path (source) or string (text)
      if builtins.isPath value then
        lib.nameValuePair targetPath { source = value; }
      else
        lib.nameValuePair targetPath { text = value; }
    ) cfg.extraConfig)

    # 3. Color Schemes (Existing logic)
    (lib.mapAttrs' (
      name: value:
      lib.nameValuePair "wezterm/colors/${name}.toml" {
        source = tomlFormat.generate "${name}.toml" { colors = value; };
      }
    ) cfg.colorSchemes)
  ];

  programs.bash.initExtra = lib.mkIf cfg.enableBashIntegration shellIntegrationStr;
  programs.zsh.initContent = lib.mkIf cfg.enableZshIntegration shellIntegrationStr;
}
