{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit
    (lib)
    literalExpression
    mkIf
    mkMerge
    mkEnableOption
    mkOption
    types
    ;

  inherit
    (types)
    attrsOf
    either
    lines
    path
    ;

  cfg = config.programs.wezterm;

  tomlFormat = pkgs.formats.toml {};

  shellIntegrationStr = ''
    source "${cfg.package}/etc/profile.d/wezterm.sh"
  '';
in {
  meta.maintainers = [
    lib.hm.maintainers.blmhemu
    lib.maintainers.khaneliman
  ];

  disabledModules = ["programs/wezterm.nix"];

  options.programs.wezterm = {
    enable = mkEnableOption "wezterm";

    package = lib.mkPackageOption pkgs "wezterm" {};

    # CHANGED: Now accepts an attribute set of paths or strings
    extraConfig = mkOption {
      type = attrsOf (either lines path);
      default = {};
      example = literalExpression ''
        {
          "appearance" = ./lua/appearance.lua;
          "keybinds.overrides" = '''
            local M = {}
            function M.apply_to_config(config)
              config.keys = { ... }
            end
            return M
          ''';
        }
      '';
      description = ''
        Attribute set of WezTerm modules.
        The key is the module namespace (e.g. `keybinds.overrides`), which corresponds
        to `require("modules.keybinds.overrides")`.
        The value is either the path to a Lua file or a string containing the Lua code.
      '';
    };

    colorSchemes = mkOption {
      type = attrsOf (tomlFormat.type);
      default = {};
      description = ''
        Attribute set of additional color schemes to be written to
        {file}`$XDG_CONFIG_HOME/wezterm/colors`.
      '';
    };

    enableBashIntegration = lib.hm.shell.mkBashIntegrationOption {inherit config;};

    enableZshIntegration = lib.hm.shell.mkZshIntegrationOption {inherit config;};
  };

  config = mkIf cfg.enable {
    home.packages = [cfg.package];

    xdg.configFile = mkMerge [
      # 1. The Main `wezterm.lua` Entry Point
      {
        "wezterm/wezterm.lua".text = ''
          -- Generated by Home Manager.
          -- See https://wezfurlong.org/wezterm/

          local wezterm = require 'wezterm'
          local config = wezterm.config_builder() -- [[@as Wezterm]]

          ${
            lib.concatLines (
              lib.mapAttrsToList
              (name: _: ''require("modules.${name}").apply_to_config(config)'')
              cfg.extraConfig
            )
          }

          return config
        '';
      }

      # 2. The Dynamic Modules (mapped from extraConfig)
      (lib.mapAttrs' (
          name: value: let
            # Convert "keybinds.overrides" -> "keybinds/overrides"
            pathName = builtins.replaceStrings ["."] ["/"] name;
            targetPath = "wezterm/modules/${pathName}.lua";
          in
            # Check if value is a path (source) or string (text)
            if builtins.isPath value
            then lib.nameValuePair targetPath {source = value;}
            else lib.nameValuePair targetPath {text = value;}
        )
        cfg.extraConfig)

      # 3. Color Schemes (Existing logic)
      (lib.mapAttrs' (
          name: value:
            lib.nameValuePair "wezterm/colors/${name}.toml" {
              source = tomlFormat.generate "${name}.toml" {colors = value;};
            }
        )
        cfg.colorSchemes)
    ];

    programs.bash.initExtra = mkIf cfg.enableBashIntegration shellIntegrationStr;
    programs.zsh.initContent = mkIf cfg.enableZshIntegration shellIntegrationStr;
  };
}
